# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Jolt < Formula
  desc "Terminal-based battery and energy monitor for macos and linux"
  homepage "https://github.com/jordond/jolt"
  url "https://github.com/jordond/jolt/archive/refs/tags/1.1.1.tar.gz"
  sha256 "c99a3bdd927b2826d3787e7d30ec743b57dd57a77b60f225c916a253fe9a39be"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jordond/jolt/releases/download/1.1.1/jolt-1.1.1-darwin-amd64.tar.gz"
      sha256 "aa54ec3f81df96881bd9fd806d631bb58982ffa8b87a98d574cb72070af369ca"
    end

    on_arm do
      url "https://github.com/jordond/jolt/releases/download/1.1.1/jolt-1.1.1-darwin-arm64.tar.gz"
      sha256 "c5b8056a86295b114d3909b56477d686290d6dfae60179e0d4a2c67f4b5ccc67"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jordond/jolt/releases/download/1.1.1/jolt-1.1.1-linux-amd64.tar.gz"
      sha256 "961071768b22b32526350471e2b40776c4345b9ceb11ab9c993978dc2635bcc3"
    end

    on_arm do
      url "https://github.com/jordond/jolt/releases/download/1.1.1/jolt-1.1.1-linux-arm64.tar.gz"
      sha256 "d8a1233459c46abf2909cf3ba9a7559ecfdc7c4548728761083936e56848b87c"
    end
  end

  def install
    bin.install "jolt"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jolt --version")
  end
end
