# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Jolt < Formula
  desc "Terminal-based battery and energy monitor for macos and linux"
  homepage "https://github.com/jordond/jolt"
  url "https://github.com/jordond/jolt/archive/refs/tags/1.0.0.tar.gz"
  sha256 "bda86b186fc779614a51e48a5c79f85eb0e8a70c7be4703e68860287f62dbf77"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jordond/jolt/releases/download/1.0.0/jolt-1.0.0-darwin-amd64.tar.gz"
      sha256 "1e1b1c5638a45aa3895470a8fc13421a71260faa02c295879111b36af479a490"
    end

    on_arm do
      url "https://github.com/jordond/jolt/releases/download/1.0.0/jolt-1.0.0-darwin-arm64.tar.gz"
      sha256 "292ebfbde18fdb02da0bba30e16c93992ae911d08dcbaea5e402aa13f9e83598"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jordond/jolt/releases/download/1.0.0/jolt-1.0.0-linux-amd64.tar.gz"
      sha256 "b7e14a32ca886abe77b6a8a80772f47b2d516d9167aa9037b46e03c370a19d79"
    end

    on_arm do
      url "https://github.com/jordond/jolt/releases/download/1.0.0/jolt-1.0.0-linux-arm64.tar.gz"
      sha256 "156b97faccd27375ebf007f39c57a592a56c962ea25b96f52f7d1ebce24f019d"
    end
  end

  def install
    bin.install "jolt"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jolt --version")
  end
end
